version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - '8080:8080'

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - '1234:1234'
    stdin_open: true
    tty: true
    depends_on:
      - backend